### ISSUE TITLE
Great app, few points and question!

### ISSUE THREAD

**Issue by Special-Niewbie** [YoCodingMonster/MSI-Dragon-Center-for-Linux-OpenFreezeCenter#5]
Hi @YoCodingMonster ,

finally thanks to you and YoyPa , the MSI laptops can be used for Linux i was waiting this few years, I really don't know in which way  and times to say THANKS for this!!!!
So, let's go to the points now, previously I have settle successfully the ISW from YoyPa, now I have discovered your app as well, so my question it's:

1. Your app it's for fresh installation? It means, because I have installed the NO GUI app ISW from YoyPa, this can go in conflict with that? Or your GUI app works combined with ISW?
2. Also, I'm using Ubuntu, and my DPI it's settled at 150%, because I have attached the monitor in 4K, I have noticed that when I'm going to open the app, the principal menu it has all the words and buttons going on top of each other , and even if you enlarge it it will keep the same shape into the window. Could be that possible to fix it?
3. For me one nice and simple future, that I have asked in the YoyPa section( here: https://github.com/YoyPa/isw/issues/185 ), it's to add the Icon in the **Desktop Bar in the Tray area** (where are the Audio, Internet and so on little icons) while the script it's running; and if not will not display it.
This will help to see if the script will run fine every time, like the original MSI DragonCenter.

I hope you can help on that , and thanks a lot for this milestone app....
Cris

**Comment by YoCodingMonster** [comment]
Thanks for appriciating....

1. The app needs fresh install means it will not work if you install it over the previous releases of itself.  It also means it will not work properly if you install it over the yopal's app.

2. Resizing is what I haven't considered, kind off it slippedmy mind and you reminded me of that, so thanks a lot for that. It will get fixed in next release

3. Right now the next big thing is battery charge and discharge threasholds. After that surely will work on that and it's a great idea. Thanks for that toooo. Will definitely give you credits in my readme files.

Feel free to leave any other bugs detected or ideas to make it better!!!

Thanks

-Adi

**Comment by Special-Niewbie** [comment]
Thanks really , if something else I will let you know for sure ;)
